In [1]:
print("Hello")

Hello


###First Project

In [14]:
import numpy as np
#Array Creation
#1D array
arr1 =np.array([10,20,30,40,50,60,70])

#2D array
arr2 =np.array([[1,2,3,4],[4,5,6,8]])
print(arr1)
print(arr2)

#Indexing
print(arr1[2])
#2D indexing
print([arr2[1,3]])

#Slicing
print(arr1[1:3])
#2D slicing
print(arr2[:,1])
print(arr2[1,:])

#Operations
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
print(a*b)
print(a**2)

#statistical Operations
a= np.array([1,2,3,4,5,6])
print("Mean:",np.mean(a))
print("Median:",np.median(a))
print("Max:",np.max(a))
print("Min:",np.min(a))
print("Sum:",np.sum(a))

#Axis-wise Operations
arr = np.array([[1,2,3],[4,5,6]])

#column-wise
print(np.sum(arr,axis=0))
#row-wise
print(np.sum(arr,axis=1))

#reshaping
arr = np.arange(1,7)
print(arr)
reshaped = arr.reshape(2,3)
print(reshaped)

#Braodcasting
a = np.array([1,2,3])
print(a + 5)

#save
np.save('a.npy', arr)

#load
loaded = np.load('a.npy')
print(loaded)

import time

#Python
lst = list(range(1000000))
start = time.time()
[i*2 for i in lst]
end = time.time()
print("List time:",end - start)

#Numpy array timing
arr =np.arange(1000000)
start = time.time()
arr*2
end = time.time()
print("Numpy time:", end - start)

[10 20 30 40 50 60 70]
[[1 2 3 4]
 [4 5 6 8]]
30
[np.int64(8)]
[20 30]
[2 5]
[4 5 6 8]
[5 7 9]
[ 4 10 18]
[1 4 9]
Mean: 3.5
Median: 3.5
Max: 6
Min: 1
Sum: 21
[5 7 9]
[ 6 15]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[6 7 8]
[1 2 3 4 5 6]
List time: 0.16423892974853516
Numpy time: 0.01848006248474121
